### ISSUE TITLE
Command conflict

### ISSUE THREAD

**Issue by Beornwulf** [vandiel01/QuestChecker#1]
`/qc` is also used by the Quest Completist addon - would it be possible to add another way of opening this addon?

**Comment by vandiel01** [comment]
what you have in mind?  /qc and /qchecker is what i have in the code.   

thought i sneak in preview:
![image](https://user-images.githubusercontent.com/52209920/99343604-dbcd6600-2853-11eb-9e9a-a876406522d6.png)

**Comment by Beornwulf** [comment]
ahah, i was not aware of the `/qchecker` command - maybe just needs that adding to the readme?
