### ISSUE TITLE
Some weirdness with the quest log.

### ISSUE THREAD

**Issue by DiscordGregory** [vandiel01/QuestChecker#2]
Van I'm pretty sure this is your fault, I thought you said you were an expert programmer :P

![image](https://i.imgur.com/4Pmvpaf.png)

It only happens if a quest is already preselected when you open the quest log, a gif to illustrate 

![image](https://i.imgur.com/ejqSKld.gif)

Apologies, I didn't have time to troubleshoot so it may be a compatibility issue with other addons.

**Comment by vandiel01** [comment]
lol all good :)  yeah might have some quirk to code, i haven't encountered that yet.   ill keep an eye out on it.  what addon you have for this quest log (if any?)

**Comment by DiscordGregory** [comment]
Nevermind, it's not your addon it's something else sorry, expert status restored 👍
