### ISSUE TITLE
GetQuestLineInfo usage

### ISSUE THREAD

**Issue by DiscordGregory** [vandiel01/QuestChecker#4]
I can't provide any context, I looked down at BugSack and saw there was an error and this was it. No idea when it occurred. 

1x Usage: local questLineInfo = C_QuestLine.GetQuestLineInfo(questID, uiMapID)
[string "=[C]"]: in function `GetQuestLineInfo'
[string "@QuestChecker\QuestChecker-2.0.lua"]:221: in function <QuestChecker\QuestChecker.lua:209>
[string "@SharedXML\C_TimerAugment.lua"]:16: in function <SharedXML\C_TimerAugment.lua:14>

Locals:
(*temporary) = "Usage: local questLineInfo = C_QuestLine.GetQuestLineInfo(questID, uiMapID)"

**Comment by vandiel01** [comment]
that one is extremely rare, VERY few quest would provide NO information at all, not even an mapid or questid or zoneid, it triggers em to fail pulling information.  Those information could be an achievement, hidden trigger that is "unreadable", i just don't know which ID are causing it.

**Comment by vandiel01** [comment]
Lemme know if this fixes the issue,, I can only hope :)  Same goes with #3

**Comment by vandiel01** [comment]
Hopefully fixed,  if not pls reopen :)
